export PATH="/Users/sirotin/bin:$PATH"
export PATH="/opt/homebrew/bin/:$PATH"
export PATH="/opt/homebrew/sbin/:$PATH"
export PATH="/Users/sirotin/go/bin:$PATH"
export PATH="/Users/sirotin/.local/bin:$PATH"