#!/bin/sh
#
# Export every keyring secret referenced by the chezmoi source templates into a
# restore script, for moving to a new machine.
#
# Usage: scripts/export-secrets.sh ~/secrets-restore.sh
#
# The output contains your secrets IN PLAINTEXT. It is written with mode 0600.
# Move it over an encrypted channel, run it on the new machine, then delete it.

set -eu

out=${1:-}
if [ -z "$out" ]; then
	echo "usage: $0 <output-file>" >&2
	exit 2
fi

if [ -e "$out" ]; then
	echo "$0: $out already exists, refusing to overwrite" >&2
	exit 1
fi

# Never drop plaintext secrets inside a git working tree.
dir=$(dirname "$out")
if git -C "$dir" rev-parse --show-toplevel >/dev/null 2>&1; then
	echo "$0: $dir is inside a git repository, pick a path outside one" >&2
	exit 1
fi

src=$(chezmoi source-path)

# Collect the service/user pairs each keyring call in the templates looks up.
# Only *.tmpl is scanned: chezmoi renders no other file, and this script would
# otherwise match its own examples.
pairs=$(grep -rhoE --include='*.tmpl' 'keyring[[:space:]]+"[^"]+"[[:space:]]+"[^"]+"' "$src" |
	sed -E 's/^keyring[[:space:]]+"([^"]+)"[[:space:]]+"([^"]+)"$/\1\t\2/' |
	sort -u)

if [ -z "$pairs" ]; then
	echo "$0: no keyring references found in $src" >&2
	exit 1
fi

umask 077
: >"$out"

cat >"$out" <<'EOF'
#!/bin/sh
# Restores keyring secrets. Generated by scripts/export-secrets.sh.
# Contains plaintext secrets: run it, then delete it.
set -eu
EOF

echo "$pairs" | while IFS="$(printf '\t')" read -r service user; do
	if ! value=$(chezmoi secret keyring get --service "$service" --user "$user" 2>/dev/null); then
		echo "missing: $service $user" >&2
		continue
	fi
	# Escape for single-quoted sh: ' becomes '\''
	escaped=$(printf '%s' "$value" | sed "s/'/'\\\\''/g")
	printf "chezmoi secret keyring set --service '%s' --user '%s' --value '%s'\n" \
		"$service" "$user" "$escaped" >>"$out"
	echo "exported: $service $user"
done

chmod 0600 "$out"

total=$(echo "$pairs" | wc -l | tr -d ' ')
echo
echo "wrote $out ($total secrets referenced by $src)"
echo "It holds plaintext secrets. Transfer it securely, run it on the new"
echo "machine, then: rm -P $out"
